# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e79507de8aaa848d47aa0ac6a32063475d85fbd15b72e46d1dcabfe26b3f7af2af5857d4e800ee844778285301232b48c05a1ddf62e6da7c4a3afaf0821ef24c

test:
  secret_key_base: 21f57dafc8f297f0b8ebab843ad3c180047accb9d7a73800a705a6b8ca9909a5c70606e29ad3fc3d541e70ea86fd8b790567a0b252f8fbba59f8a4d40bda5ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
